{{--
    Studio onboarding tour (driver.js).

    The `steps` array below is generated by the admin Tour Builder
    (Admin → Tour Builder, /admin/tour-builder). To change the tour, build it
    there, copy the "Claude prompt" export, and paste it back to update this file
    — or edit the steps array directly.

    The tour runs once per browser, gated on localStorage("ll_studio_tour_done").
--}}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/driver.js@1.3.6/dist/driver.css"/>
<script src="https://cdn.jsdelivr.net/npm/driver.js@1.3.6/dist/driver.js.iife.js"></script>
<script>
(function () {
    var TOUR_KEY = 'll_studio_tour_done';

    // Generated steps — replace this array via the Tour Builder export.
    var steps = [];

    if (!steps.length) return;                       // nothing to show yet
    if (localStorage.getItem(TOUR_KEY)) return;      // user has already seen it
    if (!window.driver || !window.driver.js) return; // driver.js failed to load

    var driver = window.driver.js.driver;
    var tour = driver({
        showProgress: true,
        allowClose: true,
        onDestroyed: function () { localStorage.setItem(TOUR_KEY, '1'); },
        steps: steps,
    });

    // Let the dashboard settle (htmx/Livewire) before starting.
    window.addEventListener('load', function () {
        setTimeout(function () { tour.drive(); }, 600);
    });
})();
</script>
