{{--
    Studio onboarding tour (driver.js).

    Generated by the admin Tour Builder (Admin → Tour Builder, /admin/tour-builder).
    To change the tour, build it there, copy the "Claude prompt" export, and paste
    it back — it updates the three generated regions below (config, steps, styles).

    The tour runs once per browser, gated on localStorage("ll_studio_tour_done").
--}}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/driver.js@1.3.6/dist/driver.css"/>
<script src="https://cdn.jsdelivr.net/npm/driver.js@1.3.6/dist/driver.js.iife.js"></script>

{{-- GENERATED:STYLE --}}
<style data-ll-tour-style></style>
{{-- /GENERATED:STYLE --}}

<script>
(function () {
    var TOUR_KEY = 'll_studio_tour_done';

    /* GENERATED:CONFIG */
    var config = {
        animate: true,
        smoothScroll: true,
        showProgress: true,
        overlayColor: '#04122b',
        overlayOpacity: 0.7,
        stagePadding: 8,
        stageRadius: 10,
        popoverClass: 'll-tour'
    };
    /* /GENERATED:CONFIG */

    /* GENERATED:STEPS */
    var steps = [];
    /* /GENERATED:STEPS */

    var AT_KEY = 'll_studio_tour_at'; // multi-page progress pointer (index into steps)

    if (!steps.length) return;                       // nothing to show yet
    try { if (window.top !== window.self) return; } catch (e) { return; } // don't run inside the Tour Builder iframe
    if (localStorage.getItem(TOUR_KEY)) return;      // user has already finished it
    if (!window.driver || !window.driver.js) return; // driver.js failed to load

    var driver = window.driver.js.driver;
    function normPath(p){ return (p || '').split('?')[0].split('#')[0].replace(/\/+$/, '') || '/'; }
    function curPath(){ return normPath(location.pathname); }
    function finish(){ localStorage.setItem(TOUR_KEY, '1'); localStorage.removeItem(AT_KEY); }

    function run(){
        var start = parseInt(localStorage.getItem(AT_KEY) || '0', 10) || 0;
        if (start >= steps.length){ finish(); return; }
        var cur = curPath();

        // Find the first remaining step that belongs to this page.
        var i = start;
        while (i < steps.length && steps[i].page && normPath(steps[i].page) !== cur) i++;
        if (i >= steps.length) return;                 // nothing for this page; wait
        if (steps[i].page && normPath(steps[i].page) !== cur) return;

        // Collect the contiguous run of steps on the current page.
        var seg = [], j = i;
        while (j < steps.length && (!steps[j].page || normPath(steps[j].page) === cur)) { seg.push(steps[j]); j++; }
        var segEnd = j, lastK = seg.length - 1;

        var tour;
        var dSteps = seg.map(function (s, k) {
            var step = { element: s.element, popover: s.popover };
            if (k === lastK && segEnd < steps.length) {
                // More pages to come — advance the pointer and navigate.
                step.onNextClick = function () {
                    localStorage.setItem(AT_KEY, String(segEnd));
                    tour.destroy();
                    location.href = steps[segEnd].page;
                };
            }
            return step;
        });

        var cfg = {};
        for (var key in config) cfg[key] = config[key];
        cfg.steps = dSteps;
        cfg.onHighlightStarted = function () { localStorage.setItem(AT_KEY, String(i + (tour ? tour.getActiveIndex() : 0))); };
        cfg.onCloseClick = function () { finish(); tour.destroy(); };       // X = end the whole tour
        cfg.onDestroyed = function () { if (segEnd >= steps.length) finish(); }; // finished the last page

        tour = driver(cfg);
        tour.drive();
    }

    // Let the page settle (htmx/Livewire) before starting/resuming.
    window.addEventListener('load', function () { setTimeout(run, 600); });
})();
</script>
